from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_BREAK, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


ROOT = Path(__file__).resolve().parents[1]
DELIVERY = ROOT / "08_delivery"
FINAL = DELIVERY / "final_v97"

PY_RUNTIME_NOTE = "Generated by build_final_handbooks_v97.py"


ARTIFACTS = [
    {
        "source": DELIVERY / "选必三_逻辑与思维_思维宝典_框架重排送审版.md",
        "markdown": FINAL / "选必三_逻辑与思维_思维宝典_最终版.md",
        "docx": FINAL / "选必三_逻辑与思维_思维宝典_最终版.docx",
        "title": "选必三《逻辑与思维》思维宝典",
        "subtitle": "按思维类型和材料触发链组织",
        "kind": "thinking",
    },
    {
        "source": DELIVERY / "选必三_逻辑与思维_推理宝典_题型重排送审版.md",
        "markdown": FINAL / "选必三_逻辑与思维_推理宝典_最终版.md",
        "docx": FINAL / "选必三_逻辑与思维_推理宝典_最终版.docx",
        "title": "选必三《逻辑与思维》推理宝典",
        "subtitle": "按同一推理形式归组",
        "kind": "reasoning",
    },
]


APPENDIX_MD = FINAL / "选必三_逻辑与思维_选择题陷阱库_最终附录.md"
APPENDIX_DOCX = FINAL / "选必三_逻辑与思维_选择题陷阱库_最终附录.docx"


def set_east_asian_font(run, font_name: str = "Microsoft YaHei") -> None:
    rpr = run._element.get_or_add_rPr()
    rfonts = rpr.rFonts
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.append(rfonts)
    rfonts.set(qn("w:eastAsia"), font_name)


def set_cell_margins(table, top=80, start=120, bottom=80, end=120) -> None:
    tbl_pr = table._tbl.tblPr
    tbl_cell_mar = tbl_pr.first_child_found_in("w:tblCellMar")
    if tbl_cell_mar is None:
        tbl_cell_mar = OxmlElement("w:tblCellMar")
        tbl_pr.append(tbl_cell_mar)
    for margin_name, value in [("top", top), ("start", start), ("bottom", bottom), ("end", end)]:
        node = tbl_cell_mar.find(qn(f"w:{margin_name}"))
        if node is None:
            node = OxmlElement(f"w:{margin_name}")
            tbl_cell_mar.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def set_table_width(table, width_dxa: int = 9360, indent_dxa: int = 120) -> None:
    tbl = table._tbl
    tbl_pr = tbl.tblPr
    tbl_w = tbl_pr.tblW
    if tbl_w is None:
        tbl_w = OxmlElement("w:tblW")
        tbl_pr.append(tbl_w)
    tbl_w.set(qn("w:w"), str(width_dxa))
    tbl_w.set(qn("w:type"), "dxa")
    tbl_ind = tbl_pr.first_child_found_in("w:tblInd")
    if tbl_ind is None:
        tbl_ind = OxmlElement("w:tblInd")
        tbl_pr.append(tbl_ind)
    tbl_ind.set(qn("w:w"), str(indent_dxa))
    tbl_ind.set(qn("w:type"), "dxa")
    set_cell_margins(table)


def configure_document(doc: Document, title: str, subtitle: str) -> None:
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.header_distance = Inches(0.492)
    section.footer_distance = Inches(0.492)

    styles = doc.styles
    normal = styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)
    normal.font.color.rgb = RGBColor(0, 0, 0)
    normal.paragraph_format.space_before = Pt(0)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.25

    for style_name, size, color, before, after in [
        ("Heading 1", 16, "2E74B5", 18, 10),
        ("Heading 2", 13, "2E74B5", 14, 7),
        ("Heading 3", 12, "1F4D78", 10, 5),
    ]:
        style = styles[style_name]
        style.font.name = "Calibri"
        style.font.size = Pt(size)
        style.font.color.rgb = RGBColor.from_string(color)
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)
        style.paragraph_format.line_spacing = 1.25

    for list_style in ["List Bullet", "List Number"]:
        style = styles[list_style]
        style.font.name = "Calibri"
        style.font.size = Pt(11)
        style.paragraph_format.left_indent = Inches(0.375)
        style.paragraph_format.first_line_indent = Inches(-0.188)
        style.paragraph_format.space_after = Pt(4)
        style.paragraph_format.line_spacing = 1.25

    header = section.header.paragraphs[0]
    header.text = title
    header.style = styles["Normal"]
    header.paragraph_format.space_after = Pt(0)
    for run in header.runs:
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(90, 90, 90)
        set_east_asian_font(run)

    footer = section.footer.paragraphs[0]
    footer.text = "选必三《逻辑与思维》复习手册"
    footer.paragraph_format.space_after = Pt(0)
    for run in footer.runs:
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(90, 90, 90)
        set_east_asian_font(run)

    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(0)
    title_p.paragraph_format.space_after = Pt(6)
    title_run = title_p.add_run(title)
    title_run.bold = True
    title_run.font.size = Pt(22)
    title_run.font.color.rgb = RGBColor.from_string("0B2545")
    set_east_asian_font(title_run)

    sub_p = doc.add_paragraph()
    sub_p.paragraph_format.space_after = Pt(12)
    sub_run = sub_p.add_run(subtitle)
    sub_run.font.size = Pt(11)
    sub_run.font.color.rgb = RGBColor(80, 80, 80)
    set_east_asian_font(sub_run)


def clean_inline(text: str) -> str:
    text = text.replace("`", "")
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = text.replace("->", "→")
    return text.strip()


def sanitize_markdown(source: Path, kind: str) -> str:
    text = source.read_text(encoding="utf-8")
    lines = text.splitlines()
    cleaned: list[str] = []
    skip_next_blank = False
    for line in lines:
        if "完整主采/可补映射见" in line:
            continue
        if line.startswith("排版边界："):
            continue
        if line.startswith("# ") and kind == "thinking":
            line = "# 选必三《逻辑与思维》思维宝典"
        elif line.startswith("# ") and kind == "reasoning":
            line = "# 选必三《逻辑与思维》推理宝典"
        line = line.replace("（框架重排版）", "")
        line = line.replace("（题型重排版）", "")
        line = line.replace("送审版", "学生版")
        line = line.replace("送审", "")
        line = line.replace("#### ", "### ")
        if "外审定位" in line or "内部" in line:
            continue
        cleaned.append(line.rstrip())
    text = "\n".join(cleaned).strip() + "\n"
    return text


def appendix_markdown() -> str:
    return """# 选必三《逻辑与思维》选择题陷阱库

本附录只收选择题错项和边界训练，不作为主观题答题模板。主观题宝典讲“材料动作 → 思维方法 → 触发逻辑 → 卷面答案句”；本附录讲“正确项为什么成立 → 错项把什么偷换了”。

## 使用规则

- 先看正确项成立的最小理由，再看错项误挂了哪个知识点。
- 不把选择题信号升格成主观题模板。只有正式主观题评分细则支持时，才进入思维宝典主线。
- 思维类选择题陷阱和推理类选择题陷阱分组复习。

## 思维类陷阱

### 思维抽象与思维具体

- 易错点：把感性认识到理性认识说得过泛；把艺术形象创造误挂为思维具体；把局部概念推进误说成已经完成思维具体。
- 学生口令：看到“从具体材料抽出理念再回到整体规定”才进思维抽象与思维具体；看到诗画意象，先查是不是形象思维或艺术创造。

### 科学思维

- 易错点：把证据互证误挂为超前思维；把定性定量分析改写成条件推理；把客观事故认定回避成普通诚信问题。
- 学生口令：证据、数据、实验、事实认定先触发客观性或可信度，不要只背“科学发展”。

### 辩证思维

- 易错点：把关键核心技术制约误写成主要方面；把辩证同一误读成取消界限；把系统优化写成部分功能之和大于整体功能。
- 学生口令：先判断题干到底给的是整体、动态、否定、矛盾转化，还是只给了选择题正确项信号。

### 创新思维

- 易错点：把发散写成单纯分析；把聚合写成散点叙事；把逆向思维泛化成“换个角度”。
- 学生口令：发散要多方向打开，聚合要集中到共同目标，逆向要有相反方向或结果倒推。

### 人机协作和治理边界

- 易错点：把价值判断、情感体验、复杂沟通交给 AI 标准化处理；把人机协同只写成技术使用。
- 学生口令：涉及价值选择和复杂沟通时，先守住人类判断主导；涉及 AI 幻觉时，先查证据和事实。

## 推理类陷阱

### 三段论

- 易错点：把大项不当扩大说成小项不当扩大；补大前提时中项不周延；只看形式有效而忘记前提真实。
- 学生口令：先找大项、小项、中项，再查周延和前提真实性。

### 假言推理和条件反推

- 易错点：必要条件反推；充分条件肯后误推；把相容选言当成不相容选言。
- 学生口令：先写 P → Q 或 Q → P，再判断能不能否定前件、肯定后件或否定一支。

### 真假关系和逻辑规律

- 易错点：把反对关系误判成矛盾关系；把同一律、矛盾律、排中律混用；不限定同一对象、同一方面。
- 学生口令：矛盾关系必一真一假，反对关系不能同真但可同假；同一律查概念，矛盾律查同一对象同一方面不能同真。

### 类比、归纳和概念外延

- 易错点：把比喻定义误作类比推理；把个别经验误作完全归纳；把具体题材和大范围题材误作交叉关系。
- 学生口令：类比要有相似属性和迁移结论，归纳要看样本是否穷尽，概念外延要先定属种、全异、交叉或相容。

## 与主观题宝典的边界

- 选择题陷阱可以帮助学生识别错项，但不能直接生成主观题答案。
- 主观题必须有材料动作、方法小帽、触发逻辑和卷面答案句四步。
- 只有选择题信号或支持性样本时，只进入本附录或边界提醒，不宣传为完整主观题模板。
"""


def add_markdown_to_doc(doc: Document, markdown: str) -> None:
    in_code = False
    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        if not line:
            continue
        if line.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            p = doc.add_paragraph(style="Normal")
            run = p.add_run(line)
            run.font.name = "Consolas"
            run.font.size = Pt(9.5)
            set_east_asian_font(run)
            continue
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            p = doc.add_paragraph(style="Heading 1")
            run = p.add_run(clean_inline(line[3:]))
        elif line.startswith("### "):
            p = doc.add_paragraph(style="Heading 2")
            run = p.add_run(clean_inline(line[4:]))
        elif line.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(clean_inline(line[2:]))
        elif re.match(r"^\d+\.\s+", line):
            p = doc.add_paragraph(style="List Number")
            run = p.add_run(clean_inline(re.sub(r"^\d+\.\s+", "", line)))
        else:
            p = doc.add_paragraph(style="Normal")
            run = p.add_run(clean_inline(line))
        set_east_asian_font(run)


def build_docx(markdown: str, docx_path: Path, title: str, subtitle: str) -> None:
    doc = Document()
    configure_document(doc, title, subtitle)
    add_markdown_to_doc(doc, markdown)
    for table in doc.tables:
        set_table_width(table)
    doc.core_properties.title = title
    doc.core_properties.subject = subtitle
    doc.core_properties.comments = "Preset: compact_reference_guide; CJK font override: Microsoft YaHei."
    doc.save(docx_path)


def main() -> None:
    FINAL.mkdir(parents=True, exist_ok=True)
    for artifact in ARTIFACTS:
        markdown = sanitize_markdown(artifact["source"], artifact["kind"])
        artifact["markdown"].write_text(markdown, encoding="utf-8")
        build_docx(markdown, artifact["docx"], artifact["title"], artifact["subtitle"])
    appendix = appendix_markdown()
    APPENDIX_MD.write_text(appendix, encoding="utf-8")
    build_docx(
        appendix,
        APPENDIX_DOCX,
        "选必三《逻辑与思维》选择题陷阱库",
        "作为双宝典的独立附录使用",
    )
    print(f"Built final artifacts in {FINAL}")


if __name__ == "__main__":
    main()
